---
title: "Fastlink Usage"
output: html_document
date: "2024-10-10"
---

```{r}
library(dplyr)

dfA <- read.csv("dfA.csv")
dfB <- read.csv("dfB.csv")
```



```{r}
library(devtools)
library(fastLink)

matches.out <- fastLink(
  dfA = dfA, dfB = dfB, 
  varnames = c("given_name", "surname", "address_1", "suburb"),
  stringdist.match = c("given_name", "surname"),
  partial.match = c("given_name", "surname"),
  return.all = TRUE
)
```

```{r}
summary(matches.out)
```

```{r}
matches.out1 <- fastLink(
  dfA = dfA, dfB = dfB, 
  varnames = c("given_name", "surname", "soc_sec_id"),
  stringdist.match = c("given_name", "surname", "soc_sec_id"),
  partial.match = c("given_name", "surname"),
  return.all = TRUE
)
```

```{r}
summary(matches.out1)
```


```{r}
threshold_prob = seq(0.7,0.99,0.01)

dfA.match <- dfA[matches.out$matches$inds.a,]
dfA.match <- na.omit(dfA.match, select=c("given_name", "surname", "address_1", "suburb"))
dfB.match <- dfB[matches.out$matches$inds.b,]
dfB.match <- na.omit(dfB.match, select=c("given_name", "surname", "address_1", "suburb"))

matched_dfs = list()
num_matches = c()

for(i in seq_along(threshold_prob)){
matched_dfs[[i]] <- getMatches(
  dfA = dfA, dfB = dfB, 
  fl.out = matches.out, threshold.match = threshold_prob[i]
)
matched_dfs[[i]] <- na.omit(matched_dfs[[i]], select=c("given_name", "surname", "address_1", "suburb"))
num_matches[i] <- nrow(matched_dfs[[i]])
}

num_matches
```

```{r}
jaccard_indices = c()

for(i in seq_along(threshold_prob)){
#intersection_size <- nrow(matched_dfs)
#union_size <- nrow(dfA) + nrow(dfB) - intersection_size

jaccard_indices[i] <- nrow(matched_dfs[[i]]) / (nrow(dfA) + nrow(dfB) - nrow(matched_dfs[[i]]))
}

```


```{r}
dfA.match1 <- dfA[matches.out1$matches$inds.a,]
dfA.match1 <- na.omit(dfA.match1, select=c("given_name", "surname", "soc_sec_id"))
dfB.match1 <- dfB[matches.out1$matches$inds.b,]
dfB.match1 <- na.omit(dfB.match1, select=c("given_name", "surname", "soc_sec_id"))

matched_dfs1 = list()
num_matches1 = c()

for(i in seq_along(threshold_prob)){
matched_dfs1[[i]] <- getMatches(
  dfA = dfA, dfB = dfB, 
  fl.out = matches.out1, threshold.match = threshold_prob[i]
)
matched_dfs1[[i]] <- na.omit(matched_dfs1[[i]], select=c("given_name", "surname", "soc_sec_id"))
num_matches1[i] <- nrow(matched_dfs1[[i]])
}

num_matches1
```

```{r}
jaccard_indices1 = c()

for(i in seq_along(threshold_prob)){
#intersection_size <- nrow(matched_dfs)
#union_size <- nrow(dfA) + nrow(dfB) - intersection_size

jaccard_indices1[i] <- nrow(matched_dfs1[[i]]) / (nrow(dfA) + nrow(dfB) - nrow(matched_dfs1[[i]]))
}

```


```{r}
library(ggplot2)
library(scales)

options(digits = 2)

plot_data <- data.frame(threshold_prob, num_matches, num_matches1)

p <- ggplot(plot_data, aes(x = threshold_prob)) + 
    geom_point(aes(y = num_matches), color = "blue") +  
    geom_line(aes(y = num_matches), color = "blue") +   
    geom_point(aes(y = num_matches1), color = "green") + 
    geom_line(aes(y = num_matches1), color = "green") + 
    labs(
        title = "Number of Matches by Threshold Probability (With NAs Removed)",
        x = "Threshold Probability",
        y = "Number of Matches"
    ) +
    theme_minimal()

print(p)
```

```{r}
plot_data <- data.frame(threshold_prob, jaccard_indices, jaccard_indices1)

p <- ggplot(plot_data, aes(x = threshold_prob)) + 
    geom_point(aes(y = jaccard_indices), color = "blue") +  
    geom_line(aes(y = jaccard_indices), color = "blue") +   
    geom_point(aes(y = jaccard_indices1), color = "green") + 
    geom_line(aes(y = jaccard_indices1), color = "green") + 
    labs(
        title = "Jaccard Index by Threshold Probability (With NAs Removed)",
        x = "Threshold Probability",
        y = "Jaccard Index"
    ) +
    theme_minimal()

print(p)
```








