---
title: "Fastlink Usage"
output: html_document
date: "2024-10-10"
---

```{r}
library(dplyr)

dfA <- read.csv("dfA.csv")
dfB <- read.csv("dfB.csv")
```



```{r}
library(devtools)
library(fastLink)

matches.out <- fastLink(
  dfA = dfA, dfB = dfB, 
  varnames = c("given_name", "surname", "street_number", "address_1", "address_2", "suburb", "postcode", "state", "date_of_birth", "soc_sec_id"),
  stringdist.match = c("given_name", "surname", "street_number", "address_1", "address_2", "suburb", "postcode", "state", "date_of_birth", "soc_sec_id"),
  partial.match = c("given_name", "surname")
)
```


```{r}
dfA.match <- dfA[matches.out$matches$inds.a,]
dfA.match <- na.omit(dfA.match)
dfB.match <- dfB[matches.out$matches$inds.b,]
dfB.match <- na.omit(dfB.match)


matched_dfs <- getMatches(
  dfA = dfA, dfB = dfB, 
  fl.out = matches.out, threshold.match = 0.7
)

matched_dfs <- na.omit(matched_dfs)

write.csv(matched_dfs, "matched.csv")
```













